#!/bin/sh
echo ``Sebutkan tiga nama panggilan teman-teman Anda xxxx yyyy zzzz``
read panggilan1 panggilan2 panggilan3
echo ``Nama panggilan teman pertama adalah : $panggilan1``
echo ``Nama panggilan teman kedua adalah : $panggilan2``
echo ``Nama panggilan teman ketiga adalah : $panggilan3``
set $panggilan1 $panggilan2 $panggilan3
echo ``Anda memiliki teman sebanyak : $#``
