#!/bin/sh
# file : percobaan_b81
# Take stderr from a command and pass it into a pipe
# for further processing.
# Uses percobaan_a81 to generate some output to stderr
# stdout of percobaan_a81 is processed normally
# Save a copy of original stdout
exec 3>&1
# stdout from percobaan_a81 is directed to the original stdout (3)
# stderr is passed into th epipe for further processing.
# stdout from the pipe is redirected back to stderr
./percobaan_a81 2>&1 1>&3 3>&- | sed 's/stderr/STDERR' 1>&2
# 3 is closed before running the command, just in case it cares
# about inheriting open file descriptors.
