#!/usr/local/bin/perl
$datafile ="./little_database";
$recordsep = "-=-\n";
open(DATA,$datafile) or die "Unable to open datafile:$!\n";
$/=$recordsep; # prepare to read in little_database file one record at a time
print "#\n\# host file- GENERATED BY $0\n# DO NOT EDIT BY HAND!\n#\n";
while (<DATA>) {
    chomp; # remove the record separator
    # split into key1,value1,...bingo, hash of record
    %record = split /:\s*|\n/m;
    print "$record{address}\t$record{name} $record{aliases}\n";
}
close(DATA);
